trigger:
- task: Docker@2
  inputs:
    containerRegistry: 'dotnetmssqlrm559597'
    repository: 'dotnetsql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dotnetmssqlpf0841g1'
    repository: 'dotnetsql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
